export const REGIST_USER_LOAD = 'REGIST_USER_LOAD';
export const REGIST_USER_SUCCESS = 'REGIST_USER_SUCCESS';
export const REGIST_USER_ERROR = 'REGIST_USER_ERROR';

export const LOGIN_USER_LOAD = 'LOGIN_USER_LOAD';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER_LOAD = 'LOGOUT_USER_LOAD';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';
